redis:
  image: redis
node1:
  build: node
  links:
    - redis
node2:
  build: node
  links:
    - redis
node3:
  build: node
  links:
    - redis
nginx:
  build: nginx
  ports:
    - "80:80"
  links:
    - node1
    - node2
    - node3
